//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using RocketScience.Services.Multiplay.Models;
using RocketScience.Services.Multiplay.Http;
using Unity.Services.Authentication.Internal;
using RocketScience.Services.Multiplay.Authentication;

namespace RocketScience.Services.Multiplay.Apis.Authentication
{
    /// <summary>
    /// Interface for the AuthenticationApiClient
    /// </summary>
    internal interface IAuthenticationApiClient
    {
            /// <summary>
            /// Async Operation.
            /// Retrieve a JWT token for use with the Unity APIs accepting a Multiplay token..
            /// </summary>
            /// <param name="request">Request object for PayloadToken.</param>
            /// <param name="operationConfiguration">Configuration for PayloadToken.</param>
            /// <returns>Task for a Response object containing status code, headers, and Models.PayloadTokenResponseBody object.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Models.PayloadTokenResponseBody>> PayloadTokenAsync(RocketScience.Services.Multiplay.Authentication.PayloadTokenRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Retrieve a Clanforge JWT token for use with legacy Clanforge payload APIs.
            /// </summary>
            /// <param name="request">Request object for PayloadTokenClanforge.</param>
            /// <param name="operationConfiguration">Configuration for PayloadTokenClanforge.</param>
            /// <returns>Task for a Response object containing status code, headers, and Models.PayloadTokenResponseBody object.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Models.PayloadTokenResponseBody>> PayloadTokenClanforgeAsync(RocketScience.Services.Multiplay.Authentication.PayloadTokenClanforgeRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IAuthenticationApiClient"/>
    internal class AuthenticationApiClient : BaseApiClient, IAuthenticationApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("http://localhost", 10, 4, null);
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
            set { _configuration = value; }
        }

        /// <summary>
        /// AuthenticationApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for AuthenticationApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> AuthenticationApiClient Configuration object.</param>
        public AuthenticationApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// Retrieve a JWT token for use with the Unity APIs accepting a Multiplay token..
        /// </summary>
        /// <param name="request">Request object for PayloadToken.</param>
        /// <param name="operationConfiguration">Configuration for PayloadToken.</param>
        /// <returns>Task for a Response object containing status code, headers, and Models.PayloadTokenResponseBody object.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Models.PayloadTokenResponseBody>> PayloadTokenAsync(RocketScience.Services.Multiplay.Authentication.PayloadTokenRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Models.PayloadTokenResponseBody)   },{"500", typeof(Models.PayloadTokenResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Models.PayloadTokenResponseBody>(response, statusCodeToTypeMap);
            return new Response<Models.PayloadTokenResponseBody>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Retrieve a Clanforge JWT token for use with legacy Clanforge payload APIs.
        /// </summary>
        /// <param name="request">Request object for PayloadTokenClanforge.</param>
        /// <param name="operationConfiguration">Configuration for PayloadTokenClanforge.</param>
        /// <returns>Task for a Response object containing status code, headers, and Models.PayloadTokenResponseBody object.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Models.PayloadTokenResponseBody>> PayloadTokenClanforgeAsync(RocketScience.Services.Multiplay.Authentication.PayloadTokenClanforgeRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Models.PayloadTokenResponseBody)   },{"500", typeof(Models.PayloadTokenResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Models.PayloadTokenResponseBody>(response, statusCodeToTypeMap);
            return new Response<Models.PayloadTokenResponseBody>(response, handledResponse);
        }

    }
}
