//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using RocketScience.Services.Multiplay.Models;
using RocketScience.Services.Multiplay.Http;
using Unity.Services.Authentication.Internal;
using RocketScience.Services.Multiplay.GameServer;

namespace RocketScience.Services.Multiplay.Apis.GameServer
{
    /// <summary>
    /// Interface for the GameServerApiClient
    /// </summary>
    internal interface IGameServerApiClient
    {
            /// <summary>
            /// Async Operation.
            /// Update the provided server and allocation ID with new state.
            /// </summary>
            /// <param name="request">Request object for PatchServerAllocation.</param>
            /// <param name="operationConfiguration">Configuration for PatchServerAllocation.</param>
            /// <returns>Task for a Response object containing status code, headers.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response> PatchServerAllocationAsync(RocketScience.Services.Multiplay.GameServer.PatchServerAllocationRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Indicates a server is ready to receive players.
            /// </summary>
            /// <param name="request">Request object for ReadyServer.</param>
            /// <param name="operationConfiguration">Configuration for ReadyServer.</param>
            /// <returns>Task for a Response object containing status code, headers, and IDeserializable object.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<IDeserializable>> ReadyServerAsync(RocketScience.Services.Multiplay.GameServer.ReadyServerRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Subscribe to game server lifecycle events.
            /// </summary>
            /// <param name="request">Request object for SubscribeServer.</param>
            /// <param name="operationConfiguration">Configuration for SubscribeServer.</param>
            /// <returns>Task for a Response object containing status code, headers.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response> SubscribeServerAsync(RocketScience.Services.Multiplay.GameServer.SubscribeServerRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Indicates a server is not ready to receive players.
            /// </summary>
            /// <param name="request">Request object for UnreadyServer.</param>
            /// <param name="operationConfiguration">Configuration for UnreadyServer.</param>
            /// <returns>Task for a Response object containing status code, headers, and IDeserializable object.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<IDeserializable>> UnreadyServerAsync(RocketScience.Services.Multiplay.GameServer.UnreadyServerRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Remove server hold by server ID.
            /// </summary>
            /// <param name="request">Request object for V1ServersServerIdHoldDelete.</param>
            /// <param name="operationConfiguration">Configuration for V1ServersServerIdHoldDelete.</param>
            /// <returns>Task for a Response object containing status code, headers.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response> V1ServersServerIdHoldDeleteAsync(RocketScience.Services.Multiplay.GameServer.V1ServersServerIdHoldDeleteRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Server hold status by server ID.
            /// </summary>
            /// <param name="request">Request object for V1ServersServerIdHoldGet.</param>
            /// <param name="operationConfiguration">Configuration for V1ServersServerIdHoldGet.</param>
            /// <returns>Task for a Response object containing status code, headers, and Models.HoldResponseBody object.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Models.HoldResponseBody>> V1ServersServerIdHoldGetAsync(RocketScience.Services.Multiplay.GameServer.V1ServersServerIdHoldGetRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Hold server by server ID.
            /// </summary>
            /// <param name="request">Request object for V1ServersServerIdHoldPost.</param>
            /// <param name="operationConfiguration">Configuration for V1ServersServerIdHoldPost.</param>
            /// <returns>Task for a Response object containing status code, headers, and Models.HoldResponseBody object.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Models.HoldResponseBody>> V1ServersServerIdHoldPostAsync(RocketScience.Services.Multiplay.GameServer.V1ServersServerIdHoldPostRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IGameServerApiClient"/>
    internal class GameServerApiClient : BaseApiClient, IGameServerApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("http://localhost", 10, 4, null);
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
            set { _configuration = value; }
        }

        /// <summary>
        /// GameServerApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for GameServerApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> GameServerApiClient Configuration object.</param>
        public GameServerApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// Update the provided server and allocation ID with new state.
        /// </summary>
        /// <param name="request">Request object for PatchServerAllocation.</param>
        /// <param name="operationConfiguration">Configuration for PatchServerAllocation.</param>
        /// <returns>Task for a Response object containing status code, headers.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response> PatchServerAllocationAsync(RocketScience.Services.Multiplay.GameServer.PatchServerAllocationRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"204",  null },{"404", typeof(Models.ErrorResponseBody)   },{"500", typeof(Models.ErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("PATCH",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            ResponseHandler.HandleAsyncResponse(response, statusCodeToTypeMap);
            return new Response(response);
        }


        /// <summary>
        /// Async Operation.
        /// Indicates a server is ready to receive players.
        /// </summary>
        /// <param name="request">Request object for ReadyServer.</param>
        /// <param name="operationConfiguration">Configuration for ReadyServer.</param>
        /// <returns>Task for a Response object containing status code, headers, and object object.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<IDeserializable>> ReadyServerAsync(RocketScience.Services.Multiplay.GameServer.ReadyServerRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(IDeserializable)   },{"404", typeof(Models.ErrorResponseBody)   },{"500", typeof(Models.ErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<IDeserializable>(response, statusCodeToTypeMap);
            return new Response<IDeserializable>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Subscribe to game server lifecycle events.
        /// </summary>
        /// <param name="request">Request object for SubscribeServer.</param>
        /// <param name="operationConfiguration">Configuration for SubscribeServer.</param>
        /// <returns>Task for a Response object containing status code, headers.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response> SubscribeServerAsync(RocketScience.Services.Multiplay.GameServer.SubscribeServerRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"101",  null },{"400", typeof(ErrorResponseBody)   },{"404", typeof(ErrorResponseBody)   },{"500", typeof(ErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            ResponseHandler.HandleAsyncResponse(response, statusCodeToTypeMap);
            return new Response(response);
        }


        /// <summary>
        /// Async Operation.
        /// Indicates a server is not ready to receive players.
        /// </summary>
        /// <param name="request">Request object for UnreadyServer.</param>
        /// <param name="operationConfiguration">Configuration for UnreadyServer.</param>
        /// <returns>Task for a Response object containing status code, headers, and object object.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<IDeserializable>> UnreadyServerAsync(RocketScience.Services.Multiplay.GameServer.UnreadyServerRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(IDeserializable)   },{"404", typeof(Models.ErrorResponseBody)   },{"500", typeof(Models.ErrorResponseBody)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<IDeserializable>(response, statusCodeToTypeMap);
            return new Response<IDeserializable>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Remove server hold by server ID.
        /// </summary>
        /// <param name="request">Request object for V1ServersServerIdHoldDelete.</param>
        /// <param name="operationConfiguration">Configuration for V1ServersServerIdHoldDelete.</param>
        /// <returns>Task for a Response object containing status code, headers.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response> V1ServersServerIdHoldDeleteAsync(RocketScience.Services.Multiplay.GameServer.V1ServersServerIdHoldDeleteRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"204",  null },{"400",  null },{"403",  null },{"404",  null },{"500",  null } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("DELETE",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            ResponseHandler.HandleAsyncResponse(response, statusCodeToTypeMap);
            return new Response(response);
        }


        /// <summary>
        /// Async Operation.
        /// Server hold status by server ID.
        /// </summary>
        /// <param name="request">Request object for V1ServersServerIdHoldGet.</param>
        /// <param name="operationConfiguration">Configuration for V1ServersServerIdHoldGet.</param>
        /// <returns>Task for a Response object containing status code, headers, and Models.HoldResponseBody object.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Models.HoldResponseBody>> V1ServersServerIdHoldGetAsync(RocketScience.Services.Multiplay.GameServer.V1ServersServerIdHoldGetRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Models.HoldResponseBody)   },{"400",  null },{"403",  null },{"404",  null },{"500",  null } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Models.HoldResponseBody>(response, statusCodeToTypeMap);
            return new Response<Models.HoldResponseBody>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Hold server by server ID.
        /// </summary>
        /// <param name="request">Request object for V1ServersServerIdHoldPost.</param>
        /// <param name="operationConfiguration">Configuration for V1ServersServerIdHoldPost.</param>
        /// <returns>Task for a Response object containing status code, headers, and Models.HoldResponseBody object.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Models.HoldResponseBody>> V1ServersServerIdHoldPostAsync(RocketScience.Services.Multiplay.GameServer.V1ServersServerIdHoldPostRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Models.HoldResponseBody)   },{"400",  null },{"403",  null },{"404",  null },{"409",  null },{"500",  null } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Models.HoldResponseBody>(response, statusCodeToTypeMap);
            return new Response<Models.HoldResponseBody>(response, handledResponse);
        }

    }
}
