//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using RocketScience.Services.Multiplay.Models;
using RocketScience.Services.Multiplay.Http;
using Unity.Services.Authentication.Internal;
using RocketScience.Services.Multiplay.Reservation;

namespace RocketScience.Services.Multiplay.Apis.Reservation
{
    /// <summary>
    /// Interface for the ReservationApiClient
    /// </summary>
    internal interface IReservationApiClient
    {
            /// <summary>
            /// Async Operation.
            /// Unreserve server by ID.
            /// </summary>
            /// <param name="request">Request object for V1ServersServerIdReservationsDelete.</param>
            /// <param name="operationConfiguration">Configuration for V1ServersServerIdReservationsDelete.</param>
            /// <returns>Task for a Response object containing status code, headers.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response> V1ServersServerIdReservationsDeleteAsync(RocketScience.Services.Multiplay.Reservation.V1ServersServerIdReservationsDeleteRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Reserve server by ID.
            /// </summary>
            /// <param name="request">Request object for V1ServersServerIdReservationsPost.</param>
            /// <param name="operationConfiguration">Configuration for V1ServersServerIdReservationsPost.</param>
            /// <returns>Task for a Response object containing status code, headers, and Models.ReserveResponseBody object.</returns>
            /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Models.ReserveResponseBody>> V1ServersServerIdReservationsPostAsync(RocketScience.Services.Multiplay.Reservation.V1ServersServerIdReservationsPostRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IReservationApiClient"/>
    internal class ReservationApiClient : BaseApiClient, IReservationApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("http://localhost", 10, 4, null);
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
            set { _configuration = value; }
        }

        /// <summary>
        /// ReservationApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for ReservationApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> ReservationApiClient Configuration object.</param>
        public ReservationApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// Unreserve server by ID.
        /// </summary>
        /// <param name="request">Request object for V1ServersServerIdReservationsDelete.</param>
        /// <param name="operationConfiguration">Configuration for V1ServersServerIdReservationsDelete.</param>
        /// <returns>Task for a Response object containing status code, headers.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response> V1ServersServerIdReservationsDeleteAsync(RocketScience.Services.Multiplay.Reservation.V1ServersServerIdReservationsDeleteRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"204",  null },{"400",  null },{"403",  null },{"404",  null },{"500",  null } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("DELETE",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            ResponseHandler.HandleAsyncResponse(response, statusCodeToTypeMap);
            return new Response(response);
        }


        /// <summary>
        /// Async Operation.
        /// Reserve server by ID.
        /// </summary>
        /// <param name="request">Request object for V1ServersServerIdReservationsPost.</param>
        /// <param name="operationConfiguration">Configuration for V1ServersServerIdReservationsPost.</param>
        /// <returns>Task for a Response object containing status code, headers, and Models.ReserveResponseBody object.</returns>
        /// <exception cref="RocketScience.Services.Multiplay.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Models.ReserveResponseBody>> V1ServersServerIdReservationsPostAsync(RocketScience.Services.Multiplay.Reservation.V1ServersServerIdReservationsPostRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Models.ReserveResponseBody)   },{"400",  null },{"403",  null },{"404",  null },{"500",  null } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Models.ReserveResponseBody>(response, statusCodeToTypeMap);
            return new Response<Models.ReserveResponseBody>(response, handledResponse);
        }

    }
}
