//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RocketScience.Services.Multiplay.Http;



namespace RocketScience.Services.Multiplay.Models
{
    /// <summary>
    /// Response to a successful hold request.
    /// </summary>
    [Preserve]
    [DataContract(Name = "HoldResponseBody")]
    internal class HoldResponseBody
    {
        /// <summary>
        /// Response to a successful hold request.
        /// </summary>
        /// <param name="expiresAt">The unix epoch when the hold will automatically expire, in seconds.</param>
        /// <param name="held">Whether the server is currently held.</param>
        [Preserve]
        public HoldResponseBody(long expiresAt, bool held)
        {
            ExpiresAt = expiresAt;
            Held = held;
        }

        /// <summary>
        /// The unix epoch when the hold will automatically expire, in seconds.
        /// </summary>
        [Preserve]
        [DataMember(Name = "expiresAt", IsRequired = true, EmitDefaultValue = true)]
        public long ExpiresAt{ get; }
        
        /// <summary>
        /// Whether the server is currently held.
        /// </summary>
        [Preserve]
        [DataMember(Name = "held", IsRequired = true, EmitDefaultValue = true)]
        public bool Held{ get; }
    
        /// <summary>
        /// Formats a HoldResponseBody into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "expiresAt," + ExpiresAt.ToString() + ",";
            serializedModel += "held," + Held.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a HoldResponseBody as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var expiresAtStringValue = ExpiresAt.ToString();
            dictionary.Add("expiresAt", expiresAtStringValue);
            
            var heldStringValue = Held.ToString();
            dictionary.Add("held", heldStringValue);
            
            return dictionary;
        }
    }
}
