//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RocketScience.Services.Multiplay.Http;



namespace RocketScience.Services.Multiplay.Models
{
    /// <summary>
    /// Request to hold a server.
    /// </summary>
    [Preserve]
    [DataContract(Name = "HoldRequestBody")]
    internal class HoldRequestBody
    {
        /// <summary>
        /// Request to hold a server.
        /// </summary>
        /// <param name="timeout">The duration of the server hold. Formatted as a duration string with a sequence of numbers and time units (e.g. 2m / 1h). Valid time units are \&quot;s\&quot; (seconds), \&quot;m\&quot; (minutes), \&quot;h\&quot; (hours). Holds are stored at a per-second granularity. </param>
        [Preserve]
        public HoldRequestBody(string timeout)
        {
            Timeout = timeout;
        }

        /// <summary>
        /// The duration of the server hold. Formatted as a duration string with a sequence of numbers and time units (e.g. 2m / 1h). Valid time units are \&quot;s\&quot; (seconds), \&quot;m\&quot; (minutes), \&quot;h\&quot; (hours). Holds are stored at a per-second granularity. 
        /// </summary>
        [Preserve]
        [DataMember(Name = "timeout", IsRequired = true, EmitDefaultValue = true)]
        public string Timeout{ get; }
    
        /// <summary>
        /// Formats a HoldRequestBody into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Timeout != null)
            {
                serializedModel += "timeout," + Timeout;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a HoldRequestBody as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Timeout != null)
            {
                var timeoutStringValue = Timeout.ToString();
                dictionary.Add("timeout", timeoutStringValue);
            }
            
            return dictionary;
        }
    }
}
