//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RocketScience.Services.Multiplay.Http;



namespace RocketScience.Services.Multiplay.Models
{
    /// <summary>
    /// PatchServerAllocationRequestBody model
    /// </summary>
    [Preserve]
    [DataContract(Name = "PatchServerAllocationRequestBody")]
    internal class PatchServerAllocationRequestBody
    {
        /// <summary>
        /// Creates an instance of PatchServerAllocationRequestBody.
        /// </summary>
        /// <param name="ready">Signal whether the server is ready to receive players.</param>
        [Preserve]
        public PatchServerAllocationRequestBody(bool ready = default)
        {
            Ready = ready;
        }

        /// <summary>
        /// Signal whether the server is ready to receive players.
        /// </summary>
        [Preserve]
        [DataMember(Name = "ready", EmitDefaultValue = true)]
        public bool Ready{ get; }
    
        /// <summary>
        /// Formats a PatchServerAllocationRequestBody into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "ready," + Ready.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a PatchServerAllocationRequestBody as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var readyStringValue = Ready.ToString();
            dictionary.Add("ready", readyStringValue);
            
            return dictionary;
        }
    }
}
