//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RocketScience.Services.Multiplay.Http;



namespace RocketScience.Services.Multiplay.Models
{
    /// <summary>
    /// ReserveResponseBody model
    /// </summary>
    [Preserve]
    [DataContract(Name = "ReserveResponseBody")]
    internal class ReserveResponseBody
    {
        /// <summary>
        /// Creates an instance of ReserveResponseBody.
        /// </summary>
        /// <param name="buildConfigurationId">The build configuration this server is using.</param>
        /// <param name="requested">The time at which the reservation was requested.</param>
        /// <param name="created">The time at which the reservation was made.</param>
        /// <param name="fulfilled">The time at which the reservation was fulfilled.</param>
        /// <param name="gamePort">The port of the server on the requested machine.</param>
        /// <param name="reservationId">The UUID of the reservation generated by the service.</param>
        /// <param name="ipv4">The IPv4 address of the machine the server is running on.</param>
        /// <param name="ipv6">The IPv6 address of the machine the server is running on.</param>
        [Preserve]
        public ReserveResponseBody(long buildConfigurationId, DateTime requested, DateTime created, DateTime fulfilled, long gamePort, System.Guid reservationId, string ipv4 = default, string ipv6 = default)
        {
            BuildConfigurationId = buildConfigurationId;
            Requested = requested;
            Created = created;
            Fulfilled = fulfilled;
            GamePort = gamePort;
            Ipv4 = ipv4;
            Ipv6 = ipv6;
            ReservationId = reservationId;
        }

        /// <summary>
        /// The build configuration this server is using.
        /// </summary>
        [Preserve]
        [DataMember(Name = "buildConfigurationId", IsRequired = true, EmitDefaultValue = true)]
        public long BuildConfigurationId{ get; }
        
        /// <summary>
        /// The time at which the reservation was requested.
        /// </summary>
        [Preserve]
        [DataMember(Name = "requested", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Requested{ get; }
        
        /// <summary>
        /// The time at which the reservation was made.
        /// </summary>
        [Preserve]
        [DataMember(Name = "created", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Created{ get; }
        
        /// <summary>
        /// The time at which the reservation was fulfilled.
        /// </summary>
        [Preserve]
        [DataMember(Name = "fulfilled", IsRequired = true, EmitDefaultValue = true)]
        public DateTime Fulfilled{ get; }
        
        /// <summary>
        /// The port of the server on the requested machine.
        /// </summary>
        [Preserve]
        [DataMember(Name = "gamePort", IsRequired = true, EmitDefaultValue = true)]
        public long GamePort{ get; }
        
        /// <summary>
        /// The IPv4 address of the machine the server is running on.
        /// </summary>
        [Preserve]
        [DataMember(Name = "ipv4", EmitDefaultValue = false)]
        public string Ipv4{ get; }
        
        /// <summary>
        /// The IPv6 address of the machine the server is running on.
        /// </summary>
        [Preserve]
        [DataMember(Name = "ipv6", EmitDefaultValue = false)]
        public string Ipv6{ get; }
        
        /// <summary>
        /// The UUID of the reservation generated by the service.
        /// </summary>
        [Preserve]
        [DataMember(Name = "reservationId", IsRequired = true, EmitDefaultValue = true)]
        public System.Guid ReservationId{ get; }
    
        /// <summary>
        /// Formats a ReserveResponseBody into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "buildConfigurationId," + BuildConfigurationId.ToString() + ",";
            if (Requested != null)
            {
                serializedModel += "requested," + Requested.ToString() + ",";
            }
            if (Created != null)
            {
                serializedModel += "created," + Created.ToString() + ",";
            }
            if (Fulfilled != null)
            {
                serializedModel += "fulfilled," + Fulfilled.ToString() + ",";
            }
            serializedModel += "gamePort," + GamePort.ToString() + ",";
            if (Ipv4 != null)
            {
                serializedModel += "ipv4," + Ipv4 + ",";
            }
            if (Ipv6 != null)
            {
                serializedModel += "ipv6," + Ipv6 + ",";
            }
            if (ReservationId != null)
            {
                serializedModel += "reservationId," + ReservationId;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a ReserveResponseBody as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var buildConfigurationIdStringValue = BuildConfigurationId.ToString();
            dictionary.Add("buildConfigurationId", buildConfigurationIdStringValue);
            
            if (Requested != null)
            {
                var requestedStringValue = Requested.ToString();
                dictionary.Add("requested", requestedStringValue);
            }
            
            if (Created != null)
            {
                var createdStringValue = Created.ToString();
                dictionary.Add("created", createdStringValue);
            }
            
            if (Fulfilled != null)
            {
                var fulfilledStringValue = Fulfilled.ToString();
                dictionary.Add("fulfilled", fulfilledStringValue);
            }
            
            var gamePortStringValue = GamePort.ToString();
            dictionary.Add("gamePort", gamePortStringValue);
            
            if (Ipv4 != null)
            {
                var ipv4StringValue = Ipv4.ToString();
                dictionary.Add("ipv4", ipv4StringValue);
            }
            
            if (Ipv6 != null)
            {
                var ipv6StringValue = Ipv6.ToString();
                dictionary.Add("ipv6", ipv6StringValue);
            }
            
            if (ReservationId != null)
            {
                var reservationIdStringValue = ReservationId.ToString();
                dictionary.Add("reservationId", reservationIdStringValue);
            }
            
            return dictionary;
        }
    }
}
