//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RocketScience.Services.Multiplay.Http;



namespace RocketScience.Services.Multiplay.Models
{
    /// <summary>
    /// UnreserveResponseBody model
    /// </summary>
    [Preserve]
    [DataContract(Name = "UnreserveResponseBody")]
    internal class UnreserveResponseBody
    {
        /// <summary>
        /// Creates an instance of UnreserveResponseBody.
        /// </summary>
        /// <param name="reservationId">The UUID of the reservation generated by the service.</param>
        [Preserve]
        public UnreserveResponseBody(System.Guid reservationId)
        {
            ReservationId = reservationId;
        }

        /// <summary>
        /// The UUID of the reservation generated by the service.
        /// </summary>
        [Preserve]
        [DataMember(Name = "reservationId", IsRequired = true, EmitDefaultValue = true)]
        public System.Guid ReservationId{ get; }
    
        /// <summary>
        /// Formats a UnreserveResponseBody into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (ReservationId != null)
            {
                serializedModel += "reservationId," + ReservationId;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a UnreserveResponseBody as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (ReservationId != null)
            {
                var reservationIdStringValue = ReservationId.ToString();
                dictionary.Add("reservationId", reservationIdStringValue);
            }
            
            return dictionary;
        }
    }
}
