//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using RocketScience.Services.Qos.Models;
using RocketScience.Services.Qos.Http;
using Unity.Services.Authentication.Internal;
using RocketScience.Services.Qos.QosDiscovery;

namespace RocketScience.Services.Qos.Apis.QosDiscovery
{
    /// <summary>
    /// Interface for the QosDiscoveryApiClient
    /// </summary>
    public interface IQosDiscoveryApiClient
    {
            /// <summary>
            /// Async Operation.
            /// List all QoS servers in fleet-regions associated with this fleet.
            /// </summary>
            /// <param name="request">Request object for ListServers.</param>
            /// <param name="operationConfiguration">Configuration for ListServers.</param>
            /// <returns>Task for a Response object containing status code, headers, and Models.QosServers object.</returns>
            /// <exception cref="RocketScience.Services.Qos.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Models.QosServers>> ListServersAsync(RocketScience.Services.Qos.QosDiscovery.ListServersRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IQosDiscoveryApiClient"/>
    public class QosDiscoveryApiClient : BaseApiClient, IQosDiscoveryApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("https://qos.multiplay.dev", 10, 4, null);
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
            set { _configuration = value; }
        }

        /// <summary>
        /// QosDiscoveryApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for QosDiscoveryApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> QosDiscoveryApiClient Configuration object.</param>
        public QosDiscoveryApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// List all QoS servers in fleet-regions associated with this fleet.
        /// </summary>
        /// <param name="request">Request object for ListServers.</param>
        /// <param name="operationConfiguration">Configuration for ListServers.</param>
        /// <returns>Task for a Response object containing status code, headers, and Models.QosServers object.</returns>
        /// <exception cref="RocketScience.Services.Qos.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Models.QosServers>> ListServersAsync(RocketScience.Services.Qos.QosDiscovery.ListServersRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Models.QosServers)   },{"304",  null },{"403",  null },{"404",  null } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Models.QosServers>(response, statusCodeToTypeMap);
            return new Response<Models.QosServers>(response, handledResponse);
        }

    }
}
