//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using NUnit.Framework;

namespace RocketScience.Services.Qos.EditorTests
{
    [TestFixture]
    public class QosDiscoveryTest
    {
        [Test]
        public void DummyTest()
        {
            Assert.IsTrue(true);
        }
    }
}
