//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RocketScience.Services.Qos.Http;



namespace RocketScience.Services.Qos.Models
{
    /// <summary>
    /// Details of a given QoS Server
    /// </summary>
    [Preserve]
    [DataContract(Name = "QosServer")]
    public class QosServer
    {
        /// <summary>
        /// Details of a given QoS Server
        /// </summary>
        /// <param name="locationid">ID of the location that this QoS server is in</param>
        /// <param name="regionid">Region ID of the qos server</param>
        /// <param name="ipv4">IPv4 address of QoS Server</param>
        /// <param name="ipv6">IPv6 address of QoS Server</param>
        /// <param name="port">Port of the QoS Server</param>
        [Preserve]
        public QosServer(long locationid, System.Guid regionid, string ipv4, string ipv6, int port)
        {
            Locationid = locationid;
            Regionid = regionid;
            Ipv4 = ipv4;
            Ipv6 = ipv6;
            Port = port;
        }

        /// <summary>
        /// ID of the location that this QoS server is in
        /// </summary>
        [Preserve]
        [DataMember(Name = "locationid", IsRequired = true, EmitDefaultValue = true)]
        public long Locationid{ get; }
        
        /// <summary>
        /// Region ID of the qos server
        /// </summary>
        [Preserve]
        [DataMember(Name = "regionid", IsRequired = true, EmitDefaultValue = true)]
        public System.Guid Regionid{ get; }
        
        /// <summary>
        /// IPv4 address of QoS Server
        /// </summary>
        [Preserve]
        [DataMember(Name = "ipv4", IsRequired = true, EmitDefaultValue = true)]
        public string Ipv4{ get; }
        
        /// <summary>
        /// IPv6 address of QoS Server
        /// </summary>
        [Preserve]
        [DataMember(Name = "ipv6", IsRequired = true, EmitDefaultValue = true)]
        public string Ipv6{ get; }
        
        /// <summary>
        /// Port of the QoS Server
        /// </summary>
        [Preserve]
        [DataMember(Name = "port", IsRequired = true, EmitDefaultValue = true)]
        public int Port{ get; }
    
        /// <summary>
        /// Formats a QosServer into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "locationid," + Locationid.ToString() + ",";
            if (Regionid != null)
            {
                serializedModel += "regionid," + Regionid + ",";
            }
            if (Ipv4 != null)
            {
                serializedModel += "ipv4," + Ipv4 + ",";
            }
            if (Ipv6 != null)
            {
                serializedModel += "ipv6," + Ipv6 + ",";
            }
            serializedModel += "port," + Port.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a QosServer as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var locationidStringValue = Locationid.ToString();
            dictionary.Add("locationid", locationidStringValue);
            
            if (Regionid != null)
            {
                var regionidStringValue = Regionid.ToString();
                dictionary.Add("regionid", regionidStringValue);
            }
            
            if (Ipv4 != null)
            {
                var ipv4StringValue = Ipv4.ToString();
                dictionary.Add("ipv4", ipv4StringValue);
            }
            
            if (Ipv6 != null)
            {
                var ipv6StringValue = Ipv6.ToString();
                dictionary.Add("ipv6", ipv6StringValue);
            }
            
            var portStringValue = Port.ToString();
            dictionary.Add("port", portStringValue);
            
            return dictionary;
        }
    }
}
