//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RocketScience.Services.Qos.Http;



namespace RocketScience.Services.Qos.Models
{
    /// <summary>
    /// List of available QoS Servers.
    /// </summary>
    [Preserve]
    [DataContract(Name = "QosServers")]
    public class QosServers
    {
        /// <summary>
        /// List of available QoS Servers.
        /// </summary>
        /// <param name="servers">servers param</param>
        [Preserve]
        public QosServers(List<QosServer> servers = default)
        {
            Servers = servers;
        }

        /// <summary>
        /// Parameter servers of QosServers
        /// </summary>
        [Preserve]
        [DataMember(Name = "servers", EmitDefaultValue = false)]
        public List<QosServer> Servers{ get; }
    
        /// <summary>
        /// Formats a QosServers into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Servers != null)
            {
                serializedModel += "servers," + Servers.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a QosServers as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
